[package]
name = "ok"
version = "0.1.0"
authors = ["thebearingedge <contact@timdav.is>"]
edition = "2018"

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
regex = "1"

[dev-dependencies]
pretty_assertions = "0.5.1"
