[package]
name = "ok"
version = "0.1.0"
authors = ["thebearingedge <contact@timdav.is>"]
edition = "2018"

[dependencies]
serde_json = "1"
serde = "1"
regex = "1"

[dev-dependencies]
maplit = "1"
pretty_assertions = "0.5.1"
